# services:
# ###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-16}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

# volumes:
# ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###

##############
# ACTUAL CODE
##############

services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:5-apache
    depends_on:
      - mariadb
    ports:
      - "80:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root

  apacheweb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    # environment:
      # DATABASE_URL: "mysql://root:root@mariadb/crudapp"
      # DATABASE_URL: "mysql://root:root@mariadb:3306/crudapp?serverVersion=10.4-MariaDB&charset=utf8mb4"


volumes:
  db_data:
